output: <%=genOutputPath%>/generated.go
package: <%=openApiGenPackage%>
generate:
  - types
  - chi-server
  - skip-prune
#  - client
#  - spec
#import-mapping:
#  ./packageA/spec.yaml: github.com/deepmap/oapi-codegen/internal/test/externalref/packageA
#  ./packageB/spec.yaml: github.com/deepmap/oapi-codegen/internal/test/externalref/packageB
