openapi: "3.0.0"
info:
  version: 1.0.0
  title: Auth Service
  description: REST API
servers:
  - url: /v1
paths:
  /health:
    get:
      description: |
        Returns health status for this application
      operationId: getHealthStatus
      responses:
        "200":
          description: Health status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "503":
          description: Service not available
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        default:
          description: error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  headers:
    IDToken:
      description: Signed ID Token to be used for calls to the API; not readable by the client (httpOnly=true) to protect against XSS attacks
      schema:
        type: string
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
    Claims:
      description: Returns all claims from user, base 64 encoded and readable from client browser
      schema:
        type: string
        example: "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ"

  parameters:
    IDToken:
      in: header
      name: IDToken
      schema:
        type: string
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"

  schemas:
    HealthStatus:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - OK
            - UNAVAILABLE
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
